- name: start kube-proxy
  systemd:
    name: kube-proxy.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: start kubelet
  systemd:
    name: kubelet.service
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: start containerd
  systemd:
    name: containerd.service
    daemon_reload: yes
    state: restarted
    enabled: yes
